### ISSUE TITLE
Chinese characters not aligned well with English letters

### ISSUE THREAD

**Issue by WangWei90** [Gruntfuggly/csv-align-mode#3]
Thank you for this work!

It works well with English letters. However, when I insert one Chinese character, it seems your extension only thinking that character occupying one space instead of two.
example (I use English comma here):

你好,谢谢,世界
hehe,hehe,hehe 

If I can make one Chinese character taking two space then some fonts will make the above example aligned.

**Comment by Gruntfuggly** [comment]
OK - I'll add a configuration option.

**Comment by WangWei90** [comment]
Thank you!
It's a great help!

**Comment by Gruntfuggly** [comment]
Hi - sorry, but I never got round to doing anything about this.

I'm not sure it is even possible because the Chinese character widths are not exactly the width of two spaces. 

I'm open to suggestions as to how it can be done?

**Comment by WangWei90** [comment]
Chinese font take 2 space using certain fonts (like "sarasa term" ).
The same problem exists in Latex tables, and this is the way to handle table alignments.

**Comment by shrft** [comment]
this is quick and dirty fix.
https://github.com/shrft/auto-align/pull/1/files

I used code from https://github.com/sindresorhus/string-width to calculate length.

**Comment by 1284685832** [comment]
> this is quick and dirty fix. https://github.com/shrft/auto-align/pull/1/files
> 
> I used code from https://github.com/sindresorhus/string-width to calculate length.

Change `width += isFullwidthCodePoint(code) ? 1.666 : 1;` to `2:1` to fix the issue.
