### ISSUE TITLE
Pad Left capability

### ISSUE THREAD

**Issue by rhyous** [Gruntfuggly/csv-align-mode#4]
I would greatly appreciate the ability to PadLeft. PadRight doesn't work well with certain data, such as doubles, float, decimals, especially money, where the decimal is always two digits.
```
ABCD, $1.00   ,
DEF , $1000.00,
```
PadLeft looks better and properly aligns decimal data that has similar digits after the decimal point.

```
ABCD,    $1.00,
 DEF, $1000.00,
```

I looked at the code. It looks like it is hardcoded to padright. It doesn't look like it would be hard to have a setting for that.

**Comment by Gruntfuggly** [comment]
I've uploaded a new version which adds an alignment setting.

**Comment by rhyous** [comment]
Awesome. I had a look and it works.

If I align left, the spaces are on the right.
If I align right, the spaces are on the left.
