### ISSUE TITLE
Ending Separater

### ISSUE THREAD

**Issue by kylegalloway** [Gruntfuggly/csv-align-mode#5]
Do you think it would be possible to add a flag for an ending separator on each line?

When flag = False:
```
| thing | other thing | last thing
```

When flag = True:
```
| thing | other thing | last thing |
```

This would make writing markdown tables easier. (Allowing me to format them with your extension without any manual tweaking afterwards.)

**Comment by Gruntfuggly** [comment]
Hi - I've just uploaded a version which adds an option for a trailing separator. Let me know if it works OK.

**Comment by kylegalloway** [comment]
It works very well. Feel free to close this issue. Thanks!
