### ISSUE TITLE
feature request: respect double quotes in csv files

### ISSUE THREAD

**Issue by patrick-m-m** [Gruntfuggly/csv-align-mode#6]
I tried to use this on a csv exported from a spreadsheet which included commas in some of the cells. The standard for escaping commas like this seems to be "double quote" around the cell contents.

When using the auto-align extension on this file, it treated these as regular separators and exploded out cells.

Please add the capability to not treat separators inside double quotes as column dividers.

Input:
```
Star Wars, Quotes
"Hello, there!", General Kenobi...
```

Output:
```
Star Wars,   Quotes
"Hello,      there!",   General Kenobi...
```
 
Desired Output:
```
Star Wars,         Quotes
"Hello, there!",   General Kenobi...
```

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should work better. Let me know if it does what you expect!
