### ISSUE TITLE
feature request: command "Align Columns By Character"

### ISSUE THREAD

**Issue by hisbvdis** [Gruntfuggly/csv-align-mode#7]
A command that allows you to align the code with the character specified in it.

Essentially, a command that combines a character command and an alignment command.

**Comment by Gruntfuggly** [comment]
Hi - I'm not sure I follow? Do you mean temporarily changing the configured character, or a one-off alignment operation?

**Comment by hisbvdis** [comment]
An alignment operation that aligns columns with a specific character, but does not change the configured base character.

**Comment by Gruntfuggly** [comment]
But wouldn't it just get realigned with the configured character?

Can you provide a simple before and after example?

**Comment by hisbvdis** [comment]
If it is possible to realize the possibility of aligning only selected code fragments, then this would allow aligning different lines with different delimiters

Described it in another issue: #8

**Comment by Gruntfuggly** [comment]
I've just added this. There is now a command:
`Auto Align: Align Selection With Separator`

**Comment by hisbvdis** [comment]
Oh yeah!
It is working.
Many thanks.
