### ISSUE TITLE
feature request: Alignment of selected code only

### ISSUE THREAD

**Issue by hisbvdis** [Gruntfuggly/csv-align-mode#8]
Setting an extension that only aligns selected code snippets

When you run the command, do not align the entire document, but only the selected code snippet

**Comment by Gruntfuggly** [comment]
OK, so a manual version of the alignment, not auto. Should be possible, although there are probably other extensions that already do that?

**Comment by hisbvdis** [comment]
I will try to find

**Comment by Gruntfuggly** [comment]
I had a quick look and couldn't find anything that looks exactly right. I'll see if I can add something...

**Comment by hisbvdis** [comment]
It is great. Thanks.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with an "Align Selection" command. It will obviously only work when auto-align is turned off.

**Comment by hisbvdis** [comment]
Yes. It works. Great

**Comment by kanlukasz** [comment]
Should this issue be still open?
I tested latest version - works fine 😉

**Comment by Gruntfuggly** [comment]
I usually leave them open for a couple of weeks to confirm that they've been fixed. Looks like I forgot about this one! Thanks.
