### ISSUE TITLE
Auto align for .robot files

### ISSUE THREAD

**Issue by f00dog-x300** [Gruntfuggly/csv-align-mode#9]
Hi!
I wanted to try using your extension to autoformat/autoalign my robot framework tests. I was I added the following in my workspace in visual studio code. 

```
  "autoAlign.associations": {
    "**/*.robot": "robot"
  },
  "autoAlign.enabled": {
    "csv": true,
    "bsv": true,
    "robot": true
  }
}

```
However, I am not seeing the option in the bottom of Visual Studio Code to autoalign. Is this a bug or maybe I'm missing something in my settings?

**Comment by Gruntfuggly** [comment]
The associations setting should indicate what separator you want to use for alignment - I don't know what .robot files are, but I guess the separator isn't "robot"?

So it should be something like:
```
"autoAlign.associations": {
    "robot": ","
  },
```

However, it should still show the status bar item. I think if you reload the window it should work. It should do it automatically though, so I'll try and fix that.

**Comment by f00dog-x300** [comment]
Thanks! I was not sure what to put on there, so I took a guess. Alignment is separated by two blank spaces or a tab.

**Comment by Gruntfuggly** [comment]
Does it work if you use those separators?

**Comment by Gruntfuggly** [comment]
I'm going to close this. If it's not working for some reason, please re-open it.
